# Generated by Django 3.2.4 on 2021-06-12 18:41

import books_project.books_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, validators=[books_project.books_app.models.validate_pages]),
        ),
    ]
